### ISSUE TITLE
Help section

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-staking-ui#5]
There should be a question mark somewhere in the UI, which, upon click opens a modal with helpful information:

- link to ToS
- quick explanation/guide
- link to source code and audits
- where to buy ADX

**NOTE:** this can just be a link to a blog post?

**Comment by alesinka** [comment]
![Staking-help](https://user-images.githubusercontent.com/24762344/73832516-f8426980-4810-11ea-9e5b-9b86a188452e.jpg)

**Comment by Ivshti** [comment]
@simzzz 

Links

* ToS: https://www.adex.network/tos
* User guide: https://www.adex.network/blog/adx-staking-is-here/
* source code and audits: https://github.com/adexnetwork/adex-protocol-eth
* where to buy ADX: https://coinmarketcap.com/currencies/adx-net/markets/

**Comment by vanina-iv** [comment]
Also, can we please place a link to the AdEx home anywhere on this page? I think it's a must.
